import { useEffect } from "react";

/**
 * Generic right-side drawer used for footer secondary links
 * (Privacy Policy, Audit Log Protocol, System Status, Contact Support).
 *
 * These links exist in the Claude/Stitch design but have no backend
 * routes. The drawer presents the static policy content and clearly
 * labels each as in development where applicable.
 */

const POLICIES = {
  privacy: {
    title: "Privacy Policy",
    devNote: "Static preview — final policy text pending legal review.",
    body: [
      {
        h: "Data we process",
        p:
          "VeriTrace processes Certificate of Analysis and Material Label files only for the purpose of structured field extraction and verification against approved master data.",
      },
      {
        h: "Where data lives",
        p:
          "Verification records are stored in the project's local audit-trail database (SQLite for the MVP). Master data is read-only and managed through controlled QA processes.",
      },
      {
        h: "Third-party services",
        p:
          "Document fields are extracted via Azure Document Intelligence. Plain-language explanations are generated by GitHub Models or a deterministic template fallback. The LLM never sets verification status.",
      },
      {
        h: "Retention",
        p:
          "Verification records are part of an immutable audit trail and cannot be edited or deleted from the UI.",
      },
    ],
  },
  audit: {
    title: "Audit Log Protocol",
    devNote:
      "Audit log export and tamper-evidence verification are in development.",
    body: [
      {
        h: "What is recorded",
        p:
          "Each verification record stores the analysis ID, decision, risk score, risk level, full set of findings with severity and score, extracted fields from both documents, source (Uploaded Document or Sample Case), and creation timestamp.",
      },
      {
        h: "Read-only by design",
        p:
          "The History page is intentionally read-only: there are no edit, delete, or override actions. This preserves the audit trail required for QA review.",
      },
      {
        h: "Final accountability",
        p:
          "The decision engine is deterministic and reviewable, but final material release decisions remain with authorized QA personnel.",
      },
    ],
  },
  status: {
    title: "System Status",
    devNote: "Public status page is in development.",
    body: [
      {
        h: "Live status pill",
        p:
          "The status pill in the header reflects a live /api/health probe of the VeriTrace backend.",
      },
      {
        h: "Component health",
        p:
          "The Settings page shows per-component status: API, Azure Document Intelligence, explanation provider, and decision engine.",
      },
      {
        h: "Incident communication",
        p:
          "A public incident history and uptime feed are not yet wired up. Contact your internal IT helpdesk for outage reports.",
      },
    ],
  },
  support: {
    title: "Contact Support",
    devNote: "Support ticket backend is in development.",
    body: [
      {
        h: "VeriTrace technical support",
        p:
          "support@veritrace.com (placeholder) — for issues with verification results or extraction quality.",
      },
      {
        h: "Internal IT & QA helpdesk",
        p:
          "helpdesk@pharmasystems.internal (placeholder) — for access, permissions, and account questions.",
      },
      {
        h: "What to include",
        p:
          "When reporting an issue, include the analysis ID from the History page along with a short description of the unexpected behavior.",
      },
    ],
  },
};

export default function PolicyDrawer({ topic, onClose }) {
  const open = Boolean(topic);
  const data = topic ? POLICIES[topic] : null;

  useEffect(() => {
    if (!open) return;
    function handleKey(e) {
      if (e.key === "Escape") onClose?.();
    }
    window.addEventListener("keydown", handleKey);
    return () => window.removeEventListener("keydown", handleKey);
  }, [open, onClose]);

  return (
    <>
      <div
        className={"drawer-backdrop" + (open ? " drawer-backdrop--shown" : "")}
        onClick={onClose}
        aria-hidden="true"
      />
      <aside
        className={"drawer" + (open ? " drawer--open" : "")}
        role="dialog"
        aria-label={data?.title || "Policy"}
        aria-hidden={!open}
      >
        <div className="drawer__header">
          <h3 className="drawer__title">{data?.title || ""}</h3>
          <button
            type="button"
            className="drawer__close"
            onClick={onClose}
            aria-label="Close"
          >
            <svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <line x1="18" y1="6" x2="6" y2="18" />
              <line x1="6" y1="6" x2="18" y2="18" />
            </svg>
          </button>
        </div>
        <div className="drawer__body">
          {data ? (
            <>
              <div className="dev-banner" style={{ marginBottom: 14 }}>
                <div className="dev-banner__icon" aria-hidden="true">
                  <svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <circle cx="12" cy="12" r="9" />
                    <line x1="12" y1="8" x2="12" y2="12" />
                    <line x1="12" y1="16" x2="12" y2="16.01" />
                  </svg>
                </div>
                <div>{data.devNote}</div>
              </div>
              {data.body.map((b) => (
                <div key={b.h}>
                  <h4>{b.h}</h4>
                  <p>{b.p}</p>
                </div>
              ))}
            </>
          ) : null}
        </div>
      </aside>
    </>
  );
}
